# Generated by Django 4.2 on 2023-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
