# Generated by Django 4.2 on 2023-04-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_info',
            old_name='title',
            new_name='blog_name',
        ),
    ]
