# Generated by Django 4.2 on 2023-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_title_blog_info_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_info',
            name='nav_logo',
            field=models.ImageField(blank=True, null=True, upload_to='nav_logo/'),
        ),
    ]
